services:
  nestjs-task-management:
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # Mount the current directory to the /app directory in the container
      - node_modules:/app/node_modules  # Use a named volume for node_modules
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - "5432:5432"

volumes:
  node_modules:
